use std::collections::HashSet;

use rand::rngs::StdRng;
use serde::{Serialize, Deserialize};

use crate::balance;
use crate::balance_config::BalanceConfig;
use crate::flaw::{self, Flaw};
use crate::location::DELTA_V_MAP;
use crate::rocket::RocketDesign;

/// Unique identifier for a rocket project.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub struct RocketProjectId(pub u64);

/// Status of a rocket design project.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RocketDesignStatus {
    InDesign { work_completed: f64, work_required: f64 },
    Testing { work_completed: f64 },
    Revising { remaining_indices: Vec<usize>, work_completed: f64 },
}

/// A rocket design project with workflow state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RocketProject {
    pub project_id: RocketProjectId,
    pub design: RocketDesign,
    pub status: RocketDesignStatus,
    pub flaws: Vec<Flaw>,
    pub revision: u32,
    pub teams_assigned: u32,
    pub complexity: u32,
    /// Cumulative engineering salary spent on this project (NRE).
    #[serde(default)]
    pub nre_cost: f64,
    /// Cumulative work spent in testing (persists across revisions).
    #[serde(default)]
    pub cumulative_testing_work: f64,
    /// Automatically start a revision as soon as testing discovers a
    /// flaw. Default on: for a project you aren't yet mass-producing,
    /// revising promptly is what you'd do anyway. Turn it off on a
    /// design with a production run going — a revision bumps
    /// `revision`, which flows onto build orders and inventory and so
    /// partially resets the learning curve.
    #[serde(default = "crate::flaw::auto_revise_default")]
    pub auto_revise: bool,
}

/// Events generated by rocket project work.
#[derive(Debug, Clone)]
pub enum RocketWorkEvent {
    DesignComplete,
    TestingCycleComplete,
    FlawDiscovered { flaw_description: String },
    RevisionComplete,
}

impl RocketProject {
    /// Create a new rocket project from a completed rocket design.
    pub fn new(
        project_id: RocketProjectId,
        design: RocketDesign,
        balance_cfg: &BalanceConfig,
    ) -> Self {
        let (total_stages, unique_engines, max_parallel) = design_stats(&design);
        let complexity = balance::rocket_complexity(total_stages, unique_engines, max_parallel);
        let work_required = balance_cfg.work.rocket_design_work_required(complexity);

        RocketProject {
            auto_revise: crate::flaw::auto_revise_default(),
            project_id,
            design,
            status: RocketDesignStatus::InDesign {
                work_completed: 0.0,
                work_required,
            },
            flaws: Vec::new(),
            revision: 0,
            teams_assigned: 0,
            complexity,
            nre_cost: 0.0,
            cumulative_testing_work: 0.0,
        }
    }

    /// Apply one day of work. Returns any completed work events.
    pub fn apply_daily_work(&mut self, rng: &mut StdRng, next_flaw_id: &mut u64, balance_cfg: &BalanceConfig) -> Vec<RocketWorkEvent> {
        if self.teams_assigned == 0 {
            return Vec::new();
        }
        let work = crate::team::effective_work_rate(self.teams_assigned);
        let mut events = Vec::new();

        match &mut self.status {
            RocketDesignStatus::InDesign { work_completed, work_required } => {
                *work_completed += work;
                if *work_completed >= *work_required {
                    self.flaws = flaw::generate_rocket_flaws(self.complexity, rng, next_flaw_id, &balance_cfg.flaws);
                    self.status = RocketDesignStatus::Testing { work_completed: 0.0 };
                    events.push(RocketWorkEvent::DesignComplete);
                }
            }
            RocketDesignStatus::Testing { work_completed } => {
                *work_completed += work;
                self.cumulative_testing_work += work;
                while *work_completed >= balance_cfg.work.testing_cycle_work {
                    *work_completed -= balance_cfg.work.testing_cycle_work;
                    let discovered = flaw::roll_discoveries_with_rng(&mut self.flaws, rng);
                    for idx in discovered {
                        events.push(RocketWorkEvent::FlawDiscovered {
                            flaw_description: self.flaws[idx].description.clone(),
                        });
                    }
                    events.push(RocketWorkEvent::TestingCycleComplete);
                }
            }
            RocketDesignStatus::Revising { remaining_indices, work_completed } => {
                *work_completed += work;
                while *work_completed >= balance_cfg.work.flaw_revision_work && !remaining_indices.is_empty() {
                    *work_completed -= balance_cfg.work.flaw_revision_work;
                    let fi = remaining_indices.remove(0);
                    self.flaws.remove(fi);
                    events.push(RocketWorkEvent::RevisionComplete);
                    for idx in remaining_indices.iter_mut() {
                        if *idx > fi {
                            *idx -= 1;
                        }
                    }
                }
                if remaining_indices.is_empty() {
                    let leftover = *work_completed;
                    self.status = RocketDesignStatus::Testing { work_completed: leftover };
                }
            }
        }

        events
    }

    /// Start revising all discovered flaws.
    pub fn start_revision(&mut self) -> bool {
        if !matches!(self.status, RocketDesignStatus::Testing { .. }) {
            return false;
        }
        let discovered_indices: Vec<usize> = self.flaws.iter()
            .enumerate()
            .filter(|(_, f)| f.discovered)
            .map(|(i, _)| i)
            .collect();
        if discovered_indices.is_empty() {
            return false;
        }
        self.revision += 1;
        self.status = RocketDesignStatus::Revising {
            remaining_indices: discovered_indices,
            work_completed: 0.0,
        };
        true
    }

    /// Number of discovered flaws.
    pub fn discovered_flaw_count(&self) -> usize {
        self.flaws.iter().filter(|f| f.discovered).count()
    }

    /// Testing level description based on cumulative work in testing.
    pub fn testing_level(&self, balance_cfg: &BalanceConfig) -> &'static str {
        let cycles = (self.cumulative_testing_work / balance_cfg.work.testing_cycle_work) as u32;
        match cycles {
            0 => "Untested",
            1..=2 => "Lightly Tested",
            3..=5 => "Moderately Tested",
            6..=9 => "Well Tested",
            _ => "Thoroughly Tested",
        }
    }
}

/// Extract design statistics for complexity calculation.
fn design_stats(design: &RocketDesign) -> (u32, u32, u32) {
    let total_stages: u32 = design.stage_groups.iter()
        .map(|g| g.len() as u32)
        .sum();

    let mut engine_ids = HashSet::new();
    for group in &design.stage_groups {
        for stage in group {
            engine_ids.insert(stage.engine.id);
        }
    }
    let unique_engines = engine_ids.len() as u32;

    let max_parallel = design.stage_groups.iter()
        .map(|g| g.len() as u32)
        .max()
        .unwrap_or(1);

    (total_stages, unique_engines, max_parallel)
}

/// Compute the maximum payload mass (in kg) that a rocket design can deliver
/// to a given destination. Returns 0.0 if the destination is unreachable.
///
/// Uses binary search over payload mass.
pub fn max_payload_to(design: &RocketDesign, from: &str, to: &str) -> f64 {
    // Ask the planner about every candidate payload rather than pricing the
    // route once at zero payload and then comparing vacuum delta-v against
    // that frozen number. The route's cost and the vehicle's usable delta-v
    // both move with payload — drag scales with mass, and gravity losses
    // scale with how sluggishly the stack leaves the pad — so a fixed
    // threshold credited heavy rockets with delta-v they never had.
    let reachable = |payload: f64| {
        DELTA_V_MAP.shortest_path_for_rocket(from, to, design, payload).is_some()
    };
    if !reachable(0.0) {
        return 0.0;
    }

    // Bracket: grow until the design can no longer make it.
    let mut lo = 0.0_f64;
    let mut hi = (design.total_mass_kg() * 2.0).max(1.0);
    while reachable(hi) && hi < 1_000_000.0 {
        hi *= 2.0;
    }

    // Feasibility is monotonic in payload, so bisect. 40 halvings take the
    // bracket well below the 1 kg the answer is rounded to.
    for _ in 0..40 {
        let mid = (lo + hi) / 2.0;
        if reachable(mid) {
            lo = mid;
        } else {
            hi = mid;
        }
    }

    // Round down to nearest kg
    lo.floor().max(0.0)
}

/// How a design's power holds up over a specific trip.
///
/// Days are counted the way the flight loop ticks them: `flight_days` is
/// how many days the craft has to keep its own lights on, and it is 1 for
/// a same-day run to LEO — the launch day itself. Calendar time from
/// launch to arrival is therefore `flight_days - 1`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TripPower {
    /// Days the craft must stay powered, launch day included. Never 0.
    pub flight_days: u32,
    /// The day its batteries run out, 1-indexed to match `flight_days`,
    /// or `None` if it arrives with the lights still on.
    pub dark_on_day: Option<u32>,
}

impl TripPower {
    pub fn survives(&self) -> bool {
        self.dark_on_day.is_none()
    }
}

/// Fly `path` and report how the design's power holds up.
///
/// Lifting the mass is only half the question. A craft running on nothing
/// but its default battery reaches LEO and hands off a payload the same
/// day, but goes dark long before it reaches Mars — and until this check
/// existed, a contract it could never survive still showed as flyable.
///
/// Flies the real route with the real daily power tick rather than
/// comparing a route length against an endurance number. Burns are flown
/// too: staging drops panels and batteries along with the tanks, so a
/// design that looks comfortable on the pad can be dark once its booster
/// is gone. Same model as the flight loop, so a craft that survives here
/// survives in flight for the same reasons.
///
/// Takes the path rather than looking it up, so a caller that already
/// planned the mission doesn't pay for a second search.
pub fn trip_power_along(
    design: &RocketDesign,
    path: &[&'static str],
    payload_kg: f64,
) -> TripPower {
    let sun_au_at = |loc: &str| {
        DELTA_V_MAP.location(loc).map_or(1.0, |l| l.sun_distance_au())
    };
    let origin = path.first().copied().unwrap_or("earth_surface");

    let mut rocket = design.instantiate(crate::rocket::RocketId(0), origin, payload_kg);
    let route = crate::flight::build_route_for_rocket(path, design, &rocket, payload_kg);

    // Every leg costs at least the day it closes on, so a route of N legs
    // is never shorter than N days however fast the transfers are.
    let flight_days: u32 = route.iter().map(|l| l.total_days().max(1)).sum::<u32>().max(1);

    let mut day = 0u32;
    for leg in &route {
        // Cruise days are billed at the departure end and the closing day
        // at the far end, matching where the flight loop thinks the craft
        // is when it charges each one. A zero-day leg is just the close.
        let cruise_days = leg.total_days().saturating_sub(1);
        let cruise_au = sun_au_at(&leg.from);
        for _ in 0..cruise_days {
            day += 1;
            if rocket.run_daily_power_tick(design, cruise_au) {
                return TripPower { flight_days, dark_on_day: Some(day) };
            }
        }
        rocket.burn_sequential(design, leg.delta_v_cost, leg.ambient_pressure_pa);
        day += 1;
        if rocket.run_daily_power_tick(design, sun_au_at(&leg.to)) {
            return TripPower { flight_days, dark_on_day: Some(day) };
        }
    }
    TripPower { flight_days, dark_on_day: None }
}

/// `trip_power_along` for callers that have endpoints rather than a path.
/// `None` when the design cannot fly the route at all.
pub fn trip_power(
    design: &RocketDesign,
    from: &str,
    to: &str,
    payload_kg: f64,
) -> Option<TripPower> {
    let (path, _) = DELTA_V_MAP.shortest_path_for_rocket(from, to, design, payload_kg)?;
    Some(trip_power_along(design, &path, payload_kg))
}

/// Whether `design` can keep its own housekeeping powered for the whole
/// trip from `from` to `to` carrying `payload_kg`. False when it cannot
/// fly the route at all.
pub fn survives_trip(design: &RocketDesign, from: &str, to: &str, payload_kg: f64) -> bool {
    trip_power(design, from, to, payload_kg).is_some_and(|p| p.survives())
}

/// Compute max payload for all reachable destinations from a given location.
/// Returns a sorted list of (destination_name, max_payload_kg).
pub fn payload_table(design: &RocketDesign, from: &str) -> Vec<(&'static str, f64)> {
    let mut results = Vec::new();
    for location in DELTA_V_MAP.locations() {
        if location.id == from {
            continue;
        }
        let payload = max_payload_to(design, from, location.id);
        if payload > 0.0 {
            results.push((location.display_name, payload));
        }
    }
    results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    results
}

/// Compute max payload for a specific list of destinations only. Used by the
/// UI to show payload feasibility just for places the player has contracts
/// for (the full 50-location table is too long to display).
pub fn payload_table_for(
    design: &RocketDesign, from: &str, destinations: &[&str],
) -> Vec<(&'static str, f64)> {
    let mut results = Vec::new();
    for &dest_id in destinations {
        if dest_id == from {
            continue;
        }
        let location = match DELTA_V_MAP.location(dest_id) {
            Some(l) => l,
            None => continue,
        };
        let payload = max_payload_to(design, from, dest_id);
        if payload > 0.0 {
            results.push((location.display_name, payload));
        }
    }
    results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    results
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::*;
    use crate::propellant::Propellant;
    use crate::stage::*;
    use rand::SeedableRng;

    fn test_rng() -> StdRng {
        StdRng::seed_from_u64(42)
    }

    fn bal() -> BalanceConfig {
        BalanceConfig::default()
    }

    fn kerolox_engine(id: u64, thrust: f64, mass: f64, isp: f64) -> EngineDesign {
        EngineDesign {
            id: EngineId(id),
            name: format!("Engine-{}", id),
            cycle: EngineCycle::GasGenerator,
            thrust_n: thrust,
            mass_kg: mass,
            isp_s: isp,
            exit_pressure_pa: 70_000.0,
            needs_atmosphere: false,
            propellant_mix: vec![
                PropellantFraction { propellant: Propellant::LOX, mass_fraction: 0.725 },
                PropellantFraction { propellant: Propellant::RP1, mass_fraction: 0.275 },
            ],
            power_draw_w: 0.0,
        }
    }

    /// Piling propellant onto a fixed engine used to *raise* reported
    /// payload without limit, because the payload search compared vacuum
    /// delta-v against a route cost that charged drag but never gravity.
    /// A stack too heavy to leave the pad was reported lifting 5.5 t to
    /// LEO — more than the same stack at four times the thrust-to-weight.
    ///
    /// Gravity is now charged against the stages that fly the ascent, so
    /// extra propellant on an engine that can't lift it is what it should
    /// be: dead weight.
    #[test]
    fn extra_propellant_cannot_buy_payload_a_weak_engine_cannot_lift() {
        let sized = |propellant: f64| {
            let engine = kerolox_engine(1, 4_000_000.0, 1_500.0, 300.0);
            RocketDesign {
                id: crate::rocket::RocketDesignId(1),
                name: "Sweep".into(),
                stage_groups: vec![vec![Stage {
                    id: StageId(1), name: "S1".into(),
                    engine, engine_count: 1,
                    propellant_mass_kg: propellant,
                    structural_mass_kg: propellant * 0.06,
                    fairing: None,
                    power_sources: Vec::new(),
                }]],
            }
        };

        // Thrust is fixed, so TWR at liftoff falls as propellant rises and
        // crosses 1.0 partway along this sweep.
        let mut best_flyable = 0.0_f64;
        for propellant in [100_000.0, 200_000.0, 300_000.0, 400_000.0,
                           500_000.0, 600_000.0, 800_000.0] {
            let design = sized(propellant);
            let twr = 4_000_000.0 / (design.total_mass_kg() * 9.81);
            let payload = max_payload_to(&design, "earth_surface", "leo");
            if twr >= 1.0 {
                best_flyable = best_flyable.max(payload);
            } else {
                assert!(payload <= best_flyable,
                    "a TWR {twr:.2} stack ({propellant:.0} kg of propellant) reported \
                     {payload:.0} kg to LEO, beating the best any flyable version of \
                     the same rocket managed ({best_flyable:.0} kg)");
            }
        }
    }

    fn simple_two_stage_design() -> RocketDesign {
        let e1 = kerolox_engine(1, 1_000_000.0, 500.0, 280.0);
        let e2 = kerolox_engine(2, 200_000.0, 100.0, 340.0);
        let s1 = Stage {
            id: StageId(1), name: "S1".into(),
            engine: e1, engine_count: 1,
            propellant_mass_kg: 50_000.0, structural_mass_kg: 3_000.0,
            fairing: None,
            power_sources: Vec::new(),
        };
        let s2 = Stage {
            id: StageId(2), name: "S2".into(),
            engine: e2, engine_count: 1,
            propellant_mass_kg: 10_000.0, structural_mass_kg: 500.0,
            fairing: None,
            power_sources: Vec::new(),
        };
        RocketDesign {
            id: crate::rocket::RocketDesignId(1),
            name: "TestRocket".into(),
            stage_groups: vec![vec![s1], vec![s2]],
        }
    }

    #[test]
    fn test_design_stats() {
        let design = simple_two_stage_design();
        let (total, unique, max_par) = design_stats(&design);
        assert_eq!(total, 2);
        assert_eq!(unique, 2);
        assert_eq!(max_par, 1);
    }

    #[test]
    fn test_new_rocket_project() {
        let design = simple_two_stage_design();
        let proj = RocketProject::new(RocketProjectId(1), design, &bal());
        assert!(matches!(proj.status, RocketDesignStatus::InDesign { .. }));
        assert_eq!(proj.teams_assigned, 0);
        assert!(proj.complexity >= 3 && proj.complexity <= 8);
    }

    #[test]
    fn test_rocket_project_design_completes() {
        let design = simple_two_stage_design();
        let mut proj = RocketProject::new(RocketProjectId(1), design, &bal());
        proj.teams_assigned = 4;
        let mut rng = test_rng();
        let mut next_flaw_id = 0u64;

        let work_needed = match &proj.status {
            RocketDesignStatus::InDesign { work_required, .. } => *work_required,
            _ => panic!("should be InDesign"),
        };

        let mut all_events = Vec::new();
        for _ in 0..(work_needed as u32 + 10) {
            let events = proj.apply_daily_work(&mut rng, &mut next_flaw_id, &bal());
            all_events.extend(events);
        }

        assert!(all_events.iter().any(|e| matches!(e, RocketWorkEvent::DesignComplete)));
        assert!(matches!(proj.status, RocketDesignStatus::Testing { .. }));
    }

    #[test]
    fn test_rocket_project_revision_fixes_all() {
        let design = simple_two_stage_design();
        let mut proj = RocketProject::new(RocketProjectId(1), design, &bal());
        proj.teams_assigned = 4;
        let mut rng = test_rng();
        let mut next_flaw_id = 0u64;

        // Advance to testing
        for _ in 0..200 {
            proj.apply_daily_work(&mut rng, &mut next_flaw_id, &bal());
        }

        // Clear any generated flaws and add controlled test flaws
        proj.flaws.clear();
        proj.flaws.push(Flaw {
            id: crate::flaw::FlawId(900),
            description: "Test flaw 1".into(),
            consequence: crate::flaw::FlawConsequence::StageLoss,
            activation_chance: 0.1,
            discovery_probability: 0.5,
            discovered: true,
            trigger: crate::flaw::FlawTrigger::PerFlight,
        });
        proj.flaws.push(Flaw {
            id: crate::flaw::FlawId(901),
            description: "Test flaw 2".into(),
            consequence: crate::flaw::FlawConsequence::EngineLoss,
            activation_chance: 0.05,
            discovery_probability: 0.3,
            discovered: true,
            trigger: crate::flaw::FlawTrigger::PerFlight,
        });

        assert_eq!(proj.flaws.len(), 2);
        assert_eq!(proj.discovered_flaw_count(), 2);
        assert!(proj.start_revision());

        for _ in 0..50 {
            proj.apply_daily_work(&mut rng, &mut next_flaw_id, &bal());
        }

        assert_eq!(proj.flaws.len(), 0);
        // Revision increments once per revision cycle, not per flaw
        assert_eq!(proj.revision, 1);
        assert!(matches!(proj.status, RocketDesignStatus::Testing { .. }));
    }

    #[test]
    fn test_max_payload_to_leo() {
        let design = simple_two_stage_design();
        let payload = max_payload_to(&design, "earth_surface", "leo");
        // Should be able to carry some payload to LEO
        assert!(payload > 0.0, "Should reach LEO with some payload, got {}", payload);
    }

    #[test]
    fn test_payload_table_not_empty() {
        let design = simple_two_stage_design();
        let table = payload_table(&design, "earth_surface");
        assert!(!table.is_empty(), "Should reach at least one destination");
    }

    #[test]
    fn test_payload_table_for_filters_to_listed_destinations() {
        let design = simple_two_stage_design();
        let dests = ["leo", "gto"];
        let table = payload_table_for(&design, "earth_surface", &dests);
        // Only LEO and GTO appear (subset of full table).
        let names: Vec<&str> = table.iter().map(|(n, _)| *n).collect();
        assert!(names.iter().any(|n| n.contains("LEO") || n.contains("Low Earth")),
            "expected LEO in {:?}", names);
        assert!(names.len() <= 2, "should not have more than 2 entries: {:?}", names);
        // Mars should not appear because it wasn't in the destinations list.
        assert!(!names.iter().any(|n| n.contains("Mars")));
    }

    #[test]
    fn test_payload_table_for_skips_unknown_destinations() {
        // Stale or otherwise unknown destination ids should be silently
        // filtered out, not crash.
        let design = simple_two_stage_design();
        let dests = ["leo", "nea", "made_up_place"];
        let table = payload_table_for(&design, "earth_surface", &dests);
        assert!(table.iter().any(|(n, _)| n.contains("LEO") || n.contains("Low Earth")));
    }

    /// Reaching a place and surviving the trip there are different
    /// questions, and the readiness colours depend on both.
    #[test]
    fn a_design_can_reach_a_destination_it_cannot_stay_alive_to_reach() {
        let bare = simple_two_stage_design();
        assert!(
            bare.stage_groups.iter().flatten().all(|s| s.power_sources.is_empty()),
            "fixture premise: nothing fitted, so every stage flies the default battery",
        );

        // LEO is a same-day trip: arrive, hand off, done. One day of
        // housekeeping is exactly what the default battery is for.
        assert!(
            max_payload_to(&bare, "earth_surface", "leo") > 0.0,
            "fixture premise: this design reaches LEO",
        );
        assert!(
            survives_trip(&bare, "earth_surface", "leo", 0.0),
            "a same-day LEO delivery is what the default battery covers",
        );

        // GTO is not: the transfer takes days the battery cannot cover, and
        // there is nothing aboard generating power.
        assert!(
            max_payload_to(&bare, "earth_surface", "gto") > 0.0,
            "fixture premise: this design can lift mass to GTO",
        );
        assert!(
            !survives_trip(&bare, "earth_surface", "gto", 0.0),
            "no generation means the craft goes dark before it arrives",
        );

        // Give the upper stage a panel that covers its own housekeeping and
        // the same trip becomes survivable — nothing about the delta-v
        // changed, only whether the lights stay on.
        let mut solar = simple_two_stage_design();
        {
            let upper = &mut solar.stage_groups[1][0];
            let demand = upper.housekeeping_w();
            upper.power_sources.push(crate::power::PowerSource::new_solar_panel(demand * 4.0));
        }
        assert!(
            survives_trip(&solar, "earth_surface", "gto", 0.0),
            "a panel that outpaces housekeeping keeps it alive the whole way",
        );
    }

    /// The designer quotes both of these numbers, so pin how days are
    /// counted: `flight_days` includes the launch day, which makes ETA
    /// `flight_days - 1` and a same-day LEO run come out as zero.
    #[test]
    fn trip_power_counts_the_launch_day_and_names_the_day_it_goes_dark() {
        let bare = simple_two_stage_design();

        let leo = trip_power(&bare, "earth_surface", "leo", 0.0)
            .expect("fixture premise: this design reaches LEO");
        assert_eq!(leo.flight_days, 1, "a single-leg ascent is one day of lights-on");
        assert_eq!(leo.dark_on_day, None, "the default battery covers exactly that");
        assert!(leo.survives());

        let gto = trip_power(&bare, "earth_surface", "gto", 0.0)
            .expect("fixture premise: this design can lift mass to GTO");
        assert!(gto.flight_days > 1, "GTO is more than one leg, so more than one day");
        assert_eq!(
            gto.dark_on_day, Some(2),
            "one day of reserve carries it through day 1 and no further",
        );
        assert!(!gto.survives());

        // A route the design cannot fly at all is not a power verdict.
        assert_eq!(trip_power(&bare, "earth_surface", "mars_surface", 0.0), None);
    }

    #[test]
    fn test_payload_decreases_with_distance() {
        let design = simple_two_stage_design();
        let leo_payload = max_payload_to(&design, "earth_surface", "leo");
        let gto_payload = max_payload_to(&design, "earth_surface", "gto");
        if gto_payload > 0.0 {
            assert!(leo_payload > gto_payload, "LEO payload {} should exceed GTO payload {}",
                leo_payload, gto_payload);
        }
    }
}
