use std::collections::HashSet;

use rand::rngs::StdRng;
use serde::{Serialize, Deserialize};

use crate::balance;
use crate::flaw::{self, Flaw, TESTING_CYCLE_WORK, FLAW_REVISION_WORK};
use crate::location::DELTA_V_MAP;
use crate::rocket::RocketDesign;

/// Unique identifier for a rocket project.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub struct RocketProjectId(pub u64);

/// Status of a rocket design project.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RocketDesignStatus {
    InDesign { work_completed: f64, work_required: f64 },
    Testing { work_completed: f64 },
    Revising { remaining_indices: Vec<usize>, work_completed: f64 },
}

/// A rocket design project with workflow state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RocketProject {
    pub project_id: RocketProjectId,
    pub design: RocketDesign,
    pub status: RocketDesignStatus,
    pub flaws: Vec<Flaw>,
    pub revision: u32,
    pub teams_assigned: u32,
    pub complexity: u32,
    /// Cumulative engineering salary spent on this project (NRE).
    #[serde(default)]
    pub nre_cost: f64,
    /// Cumulative work spent in testing (persists across revisions).
    #[serde(default)]
    pub cumulative_testing_work: f64,
}

/// Events generated by rocket project work.
#[derive(Debug, Clone)]
pub enum RocketWorkEvent {
    DesignComplete { flaw_count: u32 },
    TestingCycleComplete,
    FlawDiscovered { flaw_description: String },
    RevisionComplete,
}

impl RocketProject {
    /// Create a new rocket project from a completed rocket design.
    pub fn new(
        project_id: RocketProjectId,
        design: RocketDesign,
    ) -> Self {
        let (total_stages, unique_engines, max_parallel) = design_stats(&design);
        let complexity = balance::rocket_complexity(total_stages, unique_engines, max_parallel);
        let work_required = balance::rocket_design_work_required(complexity);

        RocketProject {
            project_id,
            design,
            status: RocketDesignStatus::InDesign {
                work_completed: 0.0,
                work_required,
            },
            flaws: Vec::new(),
            revision: 0,
            teams_assigned: 0,
            complexity,
            nre_cost: 0.0,
            cumulative_testing_work: 0.0,
        }
    }

    /// Apply one day of work. Returns any completed work events.
    pub fn apply_daily_work(&mut self, rng: &mut StdRng, next_flaw_id: &mut u64) -> Vec<RocketWorkEvent> {
        if self.teams_assigned == 0 {
            return Vec::new();
        }
        let work = crate::team::effective_work_rate(self.teams_assigned);
        let mut events = Vec::new();

        match &mut self.status {
            RocketDesignStatus::InDesign { work_completed, work_required } => {
                *work_completed += work;
                if *work_completed >= *work_required {
                    self.flaws = flaw::generate_rocket_flaws(self.complexity, rng, next_flaw_id);
                    let flaw_count = self.flaws.len() as u32;
                    self.status = RocketDesignStatus::Testing { work_completed: 0.0 };
                    events.push(RocketWorkEvent::DesignComplete { flaw_count });
                }
            }
            RocketDesignStatus::Testing { work_completed } => {
                *work_completed += work;
                self.cumulative_testing_work += work;
                while *work_completed >= TESTING_CYCLE_WORK {
                    *work_completed -= TESTING_CYCLE_WORK;
                    let discovered = flaw::roll_discoveries_with_rng(&mut self.flaws, rng);
                    for idx in discovered {
                        events.push(RocketWorkEvent::FlawDiscovered {
                            flaw_description: self.flaws[idx].description.clone(),
                        });
                    }
                    events.push(RocketWorkEvent::TestingCycleComplete);
                }
            }
            RocketDesignStatus::Revising { remaining_indices, work_completed } => {
                *work_completed += work;
                while *work_completed >= FLAW_REVISION_WORK && !remaining_indices.is_empty() {
                    *work_completed -= FLAW_REVISION_WORK;
                    let fi = remaining_indices.remove(0);
                    self.flaws.remove(fi);
                    events.push(RocketWorkEvent::RevisionComplete);
                    for idx in remaining_indices.iter_mut() {
                        if *idx > fi {
                            *idx -= 1;
                        }
                    }
                }
                if remaining_indices.is_empty() {
                    let leftover = *work_completed;
                    self.status = RocketDesignStatus::Testing { work_completed: leftover };
                }
            }
        }

        events
    }

    /// Start revising all discovered flaws.
    pub fn start_revision(&mut self) -> bool {
        if !matches!(self.status, RocketDesignStatus::Testing { .. }) {
            return false;
        }
        let discovered_indices: Vec<usize> = self.flaws.iter()
            .enumerate()
            .filter(|(_, f)| f.discovered)
            .map(|(i, _)| i)
            .collect();
        if discovered_indices.is_empty() {
            return false;
        }
        self.revision += 1;
        self.status = RocketDesignStatus::Revising {
            remaining_indices: discovered_indices,
            work_completed: 0.0,
        };
        true
    }

    /// Number of discovered flaws.
    pub fn discovered_flaw_count(&self) -> usize {
        self.flaws.iter().filter(|f| f.discovered).count()
    }

    /// Testing level description based on cumulative work in testing.
    pub fn testing_level(&self) -> &'static str {
        let cycles = (self.cumulative_testing_work / TESTING_CYCLE_WORK) as u32;
        match cycles {
            0 => "Untested",
            1..=2 => "Lightly Tested",
            3..=5 => "Moderately Tested",
            6..=9 => "Well Tested",
            _ => "Thoroughly Tested",
        }
    }
}

/// Extract design statistics for complexity calculation.
fn design_stats(design: &RocketDesign) -> (u32, u32, u32) {
    let total_stages: u32 = design.stage_groups.iter()
        .map(|g| g.len() as u32)
        .sum();

    let mut engine_ids = HashSet::new();
    for group in &design.stage_groups {
        for stage in group {
            engine_ids.insert(stage.engine.id);
        }
    }
    let unique_engines = engine_ids.len() as u32;

    let max_parallel = design.stage_groups.iter()
        .map(|g| g.len() as u32)
        .max()
        .unwrap_or(1);

    (total_stages, unique_engines, max_parallel)
}

/// Compute the maximum payload mass (in kg) that a rocket design can deliver
/// to a given destination. Returns 0.0 if the destination is unreachable.
///
/// Uses binary search over payload mass.
pub fn max_payload_to(design: &RocketDesign, from: &str, to: &str) -> f64 {
    // First check if the destination is reachable at all (with 0 payload)
    let rocket_mass = design.total_mass_kg();
    let path = DELTA_V_MAP.shortest_path(from, to, rocket_mass);
    if path.is_none() {
        return 0.0;
    }

    let required_dv = path.unwrap().1;
    let available_dv = design.total_delta_v(0.0);
    if available_dv < required_dv {
        return 0.0;
    }

    // Binary search for max payload
    let mut lo = 0.0_f64;
    let mut hi = rocket_mass * 2.0; // generous upper bound

    // First find an upper bound where we can't make it
    while design.total_delta_v(hi) >= required_dv && hi < 1_000_000.0 {
        hi *= 2.0;
    }

    for _ in 0..50 {
        let mid = (lo + hi) / 2.0;
        let dv = design.total_delta_v(mid);
        if dv >= required_dv {
            lo = mid;
        } else {
            hi = mid;
        }
    }

    // Round down to nearest kg
    lo.floor().max(0.0)
}

/// Compute max payload for all reachable destinations from a given location.
/// Returns a sorted list of (destination_name, max_payload_kg).
pub fn payload_table(design: &RocketDesign, from: &str) -> Vec<(&'static str, f64)> {
    let mut results = Vec::new();
    for location in DELTA_V_MAP.locations() {
        if location.id == from {
            continue;
        }
        let payload = max_payload_to(design, from, location.id);
        if payload > 0.0 {
            results.push((location.display_name, payload));
        }
    }
    results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    results
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::*;
    use crate::propellant::Propellant;
    use crate::stage::*;
    use rand::SeedableRng;

    fn test_rng() -> StdRng {
        StdRng::seed_from_u64(42)
    }

    fn kerolox_engine(id: u64, thrust: f64, mass: f64, isp: f64) -> EngineDesign {
        EngineDesign {
            id: EngineId(id),
            name: format!("Engine-{}", id),
            cycle: EngineCycle::GasGenerator,
            thrust_n: thrust,
            mass_kg: mass,
            isp_s: isp,
            exit_pressure_pa: 70_000.0,
            needs_atmosphere: false,
            propellant_mix: vec![
                PropellantFraction { propellant: Propellant::LOX, mass_fraction: 0.725 },
                PropellantFraction { propellant: Propellant::RP1, mass_fraction: 0.275 },
            ],
        }
    }

    fn simple_two_stage_design() -> RocketDesign {
        let e1 = kerolox_engine(1, 1_000_000.0, 500.0, 280.0);
        let e2 = kerolox_engine(2, 200_000.0, 100.0, 340.0);
        let s1 = Stage {
            id: StageId(1), name: "S1".into(),
            engine: e1, engine_count: 1,
            propellant_mass_kg: 50_000.0, structural_mass_kg: 3_000.0,
            fairing: None,
        };
        let s2 = Stage {
            id: StageId(2), name: "S2".into(),
            engine: e2, engine_count: 1,
            propellant_mass_kg: 10_000.0, structural_mass_kg: 500.0,
            fairing: None,
        };
        RocketDesign {
            id: crate::rocket::RocketDesignId(1),
            name: "TestRocket".into(),
            stage_groups: vec![vec![s1], vec![s2]],
        }
    }

    #[test]
    fn test_design_stats() {
        let design = simple_two_stage_design();
        let (total, unique, max_par) = design_stats(&design);
        assert_eq!(total, 2);
        assert_eq!(unique, 2);
        assert_eq!(max_par, 1);
    }

    #[test]
    fn test_new_rocket_project() {
        let design = simple_two_stage_design();
        let proj = RocketProject::new(RocketProjectId(1), design);
        assert!(matches!(proj.status, RocketDesignStatus::InDesign { .. }));
        assert_eq!(proj.teams_assigned, 0);
        assert!(proj.complexity >= 3 && proj.complexity <= 8);
    }

    #[test]
    fn test_rocket_project_design_completes() {
        let design = simple_two_stage_design();
        let mut proj = RocketProject::new(RocketProjectId(1), design);
        proj.teams_assigned = 4;
        let mut rng = test_rng();
        let mut next_flaw_id = 0u64;

        let work_needed = match &proj.status {
            RocketDesignStatus::InDesign { work_required, .. } => *work_required,
            _ => panic!("should be InDesign"),
        };

        let mut all_events = Vec::new();
        for _ in 0..(work_needed as u32 + 10) {
            let events = proj.apply_daily_work(&mut rng, &mut next_flaw_id);
            all_events.extend(events);
        }

        assert!(all_events.iter().any(|e| matches!(e, RocketWorkEvent::DesignComplete { .. })));
        assert!(matches!(proj.status, RocketDesignStatus::Testing { .. }));
    }

    #[test]
    fn test_rocket_project_revision_fixes_all() {
        let design = simple_two_stage_design();
        let mut proj = RocketProject::new(RocketProjectId(1), design);
        proj.teams_assigned = 4;
        let mut rng = test_rng();
        let mut next_flaw_id = 0u64;

        // Advance to testing
        for _ in 0..200 {
            proj.apply_daily_work(&mut rng, &mut next_flaw_id);
        }

        // Clear any generated flaws and add controlled test flaws
        proj.flaws.clear();
        proj.flaws.push(Flaw {
            id: crate::flaw::FlawId(900),
            description: "Test flaw 1".into(),
            consequence: crate::flaw::FlawConsequence::StageLoss,
            activation_chance: 0.1,
            discovery_probability: 0.5,
            discovered: true,
            trigger: crate::flaw::FlawTrigger::PerFlight,
        });
        proj.flaws.push(Flaw {
            id: crate::flaw::FlawId(901),
            description: "Test flaw 2".into(),
            consequence: crate::flaw::FlawConsequence::EngineLoss,
            activation_chance: 0.05,
            discovery_probability: 0.3,
            discovered: true,
            trigger: crate::flaw::FlawTrigger::PerFlight,
        });

        assert_eq!(proj.flaws.len(), 2);
        assert_eq!(proj.discovered_flaw_count(), 2);
        assert!(proj.start_revision());

        for _ in 0..50 {
            proj.apply_daily_work(&mut rng, &mut next_flaw_id);
        }

        assert_eq!(proj.flaws.len(), 0);
        // Revision increments once per revision cycle, not per flaw
        assert_eq!(proj.revision, 1);
        assert!(matches!(proj.status, RocketDesignStatus::Testing { .. }));
    }

    #[test]
    fn test_max_payload_to_leo() {
        let design = simple_two_stage_design();
        let payload = max_payload_to(&design, "earth_surface", "leo");
        // Should be able to carry some payload to LEO
        assert!(payload > 0.0, "Should reach LEO with some payload, got {}", payload);
    }

    #[test]
    fn test_payload_table_not_empty() {
        let design = simple_two_stage_design();
        let table = payload_table(&design, "earth_surface");
        assert!(!table.is_empty(), "Should reach at least one destination");
    }

    #[test]
    fn test_payload_decreases_with_distance() {
        let design = simple_two_stage_design();
        let leo_payload = max_payload_to(&design, "earth_surface", "leo");
        let gto_payload = max_payload_to(&design, "earth_surface", "gto");
        if gto_payload > 0.0 {
            assert!(leo_payload > gto_payload, "LEO payload {} should exceed GTO payload {}",
                leo_payload, gto_payload);
        }
    }
}
